-- ============================================================================
-- FieldReady — pt_holiday + working-day arithmetic.
-- 08-supabase-native-migration.md §4, §6 Step 4.
--
-- Replaces the `date-holidays` npm dependency for F17 statutory-deadline math
-- with a plain reference table + two SQL functions, so a Postgres RPC (see
-- rpc.sql's rpc_closeout_submit) can compute a working-day-aware due date
-- without any server-side JS in the path at all — "the migration makes
-- something better, not just relocated" per the design doc's own words: the
-- barrel-export bundle-leak bug this session found once already (Phase 3,
-- packages/core/src/index.ts) becomes structurally impossible for this
-- specific dependency, because there's no JS holiday library left to
-- accidentally bundle.
--
-- Seed data below is NOT hand-transcribed — it was generated by running the
-- ALREADY-INSTALLED, ALREADY-TESTED `date-holidays` package (the same one
-- packages/core/src/deadlines.ts uses, proven correct by
-- apps/api/test/phase3-proof.mjs's own Sexta-Feira Santa 2026-04-03 check)
-- day-by-day across 2024–2032, filtering to `type: "public"` only — the same
-- filter deadlines.ts's isWorkingDay() already applies, since date-holidays
-- also returns observance/optional/school/bank entries (e.g. Carnaval is
-- `observance` in Portugal, not a statutory public holiday) that must NOT
-- stop the statutory clock. A first attempt at this generation script used
-- getHolidays(year) + a naive `new Date(string).toISOString()` conversion
-- and silently shifted every date by one day (a timezone-ambiguous string
-- reparse) — caught by cross-checking against phase3-proof.mjs's own
-- already-verified 2026-04-03 assertion before trusting any of this data,
-- not assumed correct. Fixed by walking each UTC day explicitly and calling
-- hd.isHoliday() directly, the same method deadlines.ts itself uses.
--
-- Only national-level (municipality IS NULL) rows are seeded — grep across
-- seed.sql and every test fixture found tenant.municipality is never
-- actually set anywhere in this codebase today, so município-specific rows
-- would be untested, unexercised scope creep. The `municipality` column and
-- fn_add_working_days' parameter both exist and are schema-ready for
-- whenever that's needed (same "amendable later" pattern as
-- instrument_export elsewhere in this schema), same as
-- tenant.municipality itself already is.
-- ============================================================================

create table pt_holiday (
  id            uuid primary key default gen_random_uuid(),
  holiday_date  date not null,
  name          text not null,
  kind          text not null check (kind in ('public', 'observance', 'optional', 'school', 'bank')),
  municipality  text  -- date-holidays subdivision code, e.g. 'PT-11' — null = national. Never populated yet.
);

comment on table pt_holiday is
  'Reference data, not tenant-scoped — readable by every authenticated '
  'session, writable only by a migration/reseed (no INSERT/UPDATE/DELETE '
  'grant to authenticated below). Regenerable yearly per the design doc''s '
  'own note; see this file''s header for exactly how these rows were '
  'produced.';

-- Postgres UNIQUE constraints treat every NULL as distinct, so a plain
-- unique(holiday_date, municipality) would not actually stop a duplicate
-- national row (municipality IS NULL) from being inserted twice — an
-- expression index normalizing null to '' is what actually enforces it.
create unique index idx_pt_holiday_date_municipality on pt_holiday (holiday_date, coalesce(municipality, ''));

insert into pt_holiday (holiday_date, name, kind, municipality) values
  ('2024-01-01', 'Ano Novo', 'public', null),
  ('2024-03-29', 'Sexta-Feira Santa', 'public', null),
  ('2024-03-31', 'Páscoa', 'public', null),
  ('2024-04-25', 'Dia da Liberdade', 'public', null),
  ('2024-05-01', 'Dia do trabalhador', 'public', null),
  ('2024-05-30', 'Corpo de Deus', 'public', null),
  ('2024-06-10', 'Dia de Portugal', 'public', null),
  ('2024-08-15', 'Assunção de Maria', 'public', null),
  ('2024-10-05', 'Implantação da República', 'public', null),
  ('2024-11-01', 'Todos os santos', 'public', null),
  ('2024-12-01', 'Restauração da Independência', 'public', null),
  ('2024-12-08', 'Imaculada Conceição', 'public', null),
  ('2024-12-25', 'Natal', 'public', null),
  ('2025-01-01', 'Ano Novo', 'public', null),
  ('2025-04-18', 'Sexta-Feira Santa', 'public', null),
  ('2025-04-20', 'Páscoa', 'public', null),
  ('2025-04-25', 'Dia da Liberdade', 'public', null),
  ('2025-05-01', 'Dia do trabalhador', 'public', null),
  ('2025-06-10', 'Dia de Portugal', 'public', null),
  ('2025-06-19', 'Corpo de Deus', 'public', null),
  ('2025-08-15', 'Assunção de Maria', 'public', null),
  ('2025-10-05', 'Implantação da República', 'public', null),
  ('2025-11-01', 'Todos os santos', 'public', null),
  ('2025-12-01', 'Restauração da Independência', 'public', null),
  ('2025-12-08', 'Imaculada Conceição', 'public', null),
  ('2025-12-25', 'Natal', 'public', null),
  ('2026-01-01', 'Ano Novo', 'public', null),
  ('2026-04-03', 'Sexta-Feira Santa', 'public', null),
  ('2026-04-05', 'Páscoa', 'public', null),
  ('2026-04-25', 'Dia da Liberdade', 'public', null),
  ('2026-05-01', 'Dia do trabalhador', 'public', null),
  ('2026-06-04', 'Corpo de Deus', 'public', null),
  ('2026-06-10', 'Dia de Portugal', 'public', null),
  ('2026-08-15', 'Assunção de Maria', 'public', null),
  ('2026-10-05', 'Implantação da República', 'public', null),
  ('2026-11-01', 'Todos os santos', 'public', null),
  ('2026-12-01', 'Restauração da Independência', 'public', null),
  ('2026-12-08', 'Imaculada Conceição', 'public', null),
  ('2026-12-25', 'Natal', 'public', null),
  ('2027-01-01', 'Ano Novo', 'public', null),
  ('2027-03-26', 'Sexta-Feira Santa', 'public', null),
  ('2027-03-28', 'Páscoa', 'public', null),
  ('2027-04-25', 'Dia da Liberdade', 'public', null),
  ('2027-05-01', 'Dia do trabalhador', 'public', null),
  ('2027-05-27', 'Corpo de Deus', 'public', null),
  ('2027-06-10', 'Dia de Portugal', 'public', null),
  ('2027-08-15', 'Assunção de Maria', 'public', null),
  ('2027-10-05', 'Implantação da República', 'public', null),
  ('2027-11-01', 'Todos os santos', 'public', null),
  ('2027-12-01', 'Restauração da Independência', 'public', null),
  ('2027-12-08', 'Imaculada Conceição', 'public', null),
  ('2027-12-25', 'Natal', 'public', null),
  ('2028-01-01', 'Ano Novo', 'public', null),
  ('2028-04-14', 'Sexta-Feira Santa', 'public', null),
  ('2028-04-16', 'Páscoa', 'public', null),
  ('2028-04-25', 'Dia da Liberdade', 'public', null),
  ('2028-05-01', 'Dia do trabalhador', 'public', null),
  ('2028-06-10', 'Dia de Portugal', 'public', null),
  ('2028-06-15', 'Corpo de Deus', 'public', null),
  ('2028-08-15', 'Assunção de Maria', 'public', null),
  ('2028-10-05', 'Implantação da República', 'public', null),
  ('2028-11-01', 'Todos os santos', 'public', null),
  ('2028-12-01', 'Restauração da Independência', 'public', null),
  ('2028-12-08', 'Imaculada Conceição', 'public', null),
  ('2028-12-25', 'Natal', 'public', null),
  ('2029-01-01', 'Ano Novo', 'public', null),
  ('2029-03-30', 'Sexta-Feira Santa', 'public', null),
  ('2029-04-01', 'Páscoa', 'public', null),
  ('2029-04-25', 'Dia da Liberdade', 'public', null),
  ('2029-05-01', 'Dia do trabalhador', 'public', null),
  ('2029-05-31', 'Corpo de Deus', 'public', null),
  ('2029-06-10', 'Dia de Portugal', 'public', null),
  ('2029-08-15', 'Assunção de Maria', 'public', null),
  ('2029-10-05', 'Implantação da República', 'public', null),
  ('2029-11-01', 'Todos os santos', 'public', null),
  ('2029-12-01', 'Restauração da Independência', 'public', null),
  ('2029-12-08', 'Imaculada Conceição', 'public', null),
  ('2029-12-25', 'Natal', 'public', null),
  ('2030-01-01', 'Ano Novo', 'public', null),
  ('2030-04-19', 'Sexta-Feira Santa', 'public', null),
  ('2030-04-21', 'Páscoa', 'public', null),
  ('2030-04-25', 'Dia da Liberdade', 'public', null),
  ('2030-05-01', 'Dia do trabalhador', 'public', null),
  ('2030-06-10', 'Dia de Portugal', 'public', null),
  ('2030-06-20', 'Corpo de Deus', 'public', null),
  ('2030-08-15', 'Assunção de Maria', 'public', null),
  ('2030-10-05', 'Implantação da República', 'public', null),
  ('2030-11-01', 'Todos os santos', 'public', null),
  ('2030-12-01', 'Restauração da Independência', 'public', null),
  ('2030-12-08', 'Imaculada Conceição', 'public', null),
  ('2030-12-25', 'Natal', 'public', null),
  ('2031-01-01', 'Ano Novo', 'public', null),
  ('2031-04-11', 'Sexta-Feira Santa', 'public', null),
  ('2031-04-13', 'Páscoa', 'public', null),
  ('2031-04-25', 'Dia da Liberdade', 'public', null),
  ('2031-05-01', 'Dia do trabalhador', 'public', null),
  ('2031-06-10', 'Dia de Portugal', 'public', null),
  ('2031-06-12', 'Corpo de Deus', 'public', null),
  ('2031-08-15', 'Assunção de Maria', 'public', null),
  ('2031-10-05', 'Implantação da República', 'public', null),
  ('2031-11-01', 'Todos os santos', 'public', null),
  ('2031-12-01', 'Restauração da Independência', 'public', null),
  ('2031-12-08', 'Imaculada Conceição', 'public', null),
  ('2031-12-25', 'Natal', 'public', null),
  ('2032-01-01', 'Ano Novo', 'public', null),
  ('2032-03-26', 'Sexta-Feira Santa', 'public', null),
  ('2032-03-28', 'Páscoa', 'public', null),
  ('2032-04-25', 'Dia da Liberdade', 'public', null),
  ('2032-05-01', 'Dia do trabalhador', 'public', null),
  ('2032-05-27', 'Corpo de Deus', 'public', null),
  ('2032-06-10', 'Dia de Portugal', 'public', null),
  ('2032-08-15', 'Assunção de Maria', 'public', null),
  ('2032-10-05', 'Implantação da República', 'public', null),
  ('2032-11-01', 'Todos os santos', 'public', null),
  ('2032-12-01', 'Restauração da Independência', 'public', null),
  ('2032-12-08', 'Imaculada Conceição', 'public', null),
  ('2032-12-25', 'Natal', 'public', null);

alter table pt_holiday enable row level security;
alter table pt_holiday force row level security;
create policy pt_holiday_select on pt_holiday for select using (true);
grant select on pt_holiday to authenticated;

-- fn_is_working_day: byte-faithful port of packages/core/src/deadlines.ts's
-- isWorkingDay() — not a Saturday/Sunday, and no `public`-kind holiday on
-- this date (national, or matching p_municipality when given). extract(dow
-- from date) returns 0=Sunday..6=Saturday for a `date` value, same numbering
-- JS's Date.getUTCDay() uses, so the weekend check is the same comparison,
-- not just the same intent.
create or replace function fn_is_working_day(p_date date, p_municipality text default null)
returns boolean
language sql
stable
as $$
  select extract(dow from p_date) not in (0, 6)
    and not exists (
      select 1 from pt_holiday
      where holiday_date = p_date
        and kind = 'public'
        and (municipality is null or municipality = p_municipality)
    );
$$;

-- fn_add_working_days: byte-faithful port of addWorkingDays() — same
-- "day the fromDate itself falls on is never counted" semantics (the loop
-- always advances the cursor before checking), same "count only forward"
-- direction (p_days is assumed positive, same as the ported function never
-- handled negative/zero specially either).
create or replace function fn_add_working_days(p_from_date date, p_days int, p_municipality text default null)
returns date
language plpgsql
stable
as $$
declare
  v_cursor date := p_from_date;
  v_remaining int := p_days;
begin
  while v_remaining > 0 loop
    v_cursor := v_cursor + 1;
    if fn_is_working_day(v_cursor, p_municipality) then
      v_remaining := v_remaining - 1;
    end if;
  end loop;
  return v_cursor;
end;
$$;

comment on function fn_add_working_days(date, int, text) is
  'Port of packages/core/src/deadlines.ts addWorkingDays(). Verified against '
  'the same real disagreement apps/api/test/phase3-proof.mjs already proves '
  '(termo issued 2026-04-01, naive answer 2026-04-15, holiday-aware answer '
  '2026-04-16, skipping Sexta-Feira Santa 2026-04-03) — '
  'verify-holidays-supabase.mjs re-derives this exact case against this '
  'table/function pair, not a different one, so the two implementations '
  'can''t silently drift onto different "correct" answers.';
